qq:
   music:
         url: https://c.y.qq.com/rsc/fcgi-bin/fcg_get_profile_homepage.fcg?g_tk=590160334&jsonpCallback=MusicJsonCallback04161809824877283&loginUin=1269482535&hostUin=0&format=jsonp&inCharset=utf8&outCharset=utf-8&notice=0&platform=yqq&needNewCode=0&cid=205360838&ct=20&userid=1269482535&reqfrom=1&reqtype=0